[project]
name = "ris-sem-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=50.0.2",
    "dilithium-py>=1.4.0",
    "numpy>=2.5.3",
]

[project.scripts]
ris-sem-project = "ris_sem_project:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
